server:
  port: 10000

spring:
  application:
    name: gulimall-product
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  thymeleaf:
    cache: true
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
    # 过期时间
    redis:
      time-to-live: 3600000
      # 是否开启前缀，默认为true
      use-key-prefix: true
      # 键的前缀，如果不配置，默认就是缓存名cacheNames
#      key-prefix: CACHE_
      # 是否缓存空置，防止缓存穿透，默认为true
      cache-null-values: true
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

logging:
  level:
    com.atguigu.gulimall: debug