spring:
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: https://www.sina.com.cn
          predicates:
           - Query=url,sina

        - id: qq_route
          uri: https://www.qq.com
          predicates:
           - Query=url,qq