spring:
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: https://www.sina.com.cn
          predicates:
           - Query=url,sina

        - id: qq_route
          uri: https://www.qq.com
          predicates:
           - Query=url,qq

        - id: product_route
          uri: lb://gulimall-product
          predicates:
           - Path=/api/product/**
          filters:
           - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: third_party_route
          uri: lb://gulimall-third-party
          predicates:
           - Path=/api/thirdparty/**
          filters:
           - RewritePath=/api/thirdparty(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
           - Path=/api/**
          filters: # 比如验证码，http://localhost:88/api/captcha.jpg?uuid=c592925c-af7e-415b-83dc-79c28a87351d  转为
           - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}